# Generated by Django 5.2.8 on 2025-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(choices=[('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('bulk_import_started', 'Bulk Import Started'), ('bulk_import_completed', 'Bulk Import Completed'), ('bulk_import_failed', 'Bulk Import Failed')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),  # pyright: ignore[reportArgumentType]
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
    ]
