# Generated by Django 5.2.8 on 2025-11-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
